const dispUserNameTD = document.getElementById("userNameTD")
const dispContactTD = document.getElementById("contactTD")
const dispPaperSizeTD= document.getElementById("paperSizeTD")
const dispPaperTypeTD =document.getElementById("paperTypeTD")
const dispPrintingSidesTD = document.getElementById("printingSidesTD")
const dispPrintingcolorTD = document.getElementById("PrintingColorTD")
const dispFileName = document.getElementById("fileName")
const dispPageTD = document.getElementById("noOfPagesTD")
const dispCopies = document.getElementById("noOfCopies")
const dispTotalPriceTd = document.getElementById("totalPriceTD")
const dispDateTD = document.getElementById("dateTD")
const dispTimeTD = document.getElementById("timeTD")
const dispPaymentMethodTD = document.getElementById("paymentMethodTD")
const dispPaymentStatusTD = document.getElementById("paymentStatusOPTIONS")
const dispDeliveryStatusTD = document.getElementById("deliveryStatusOPTION")


const dispPendingPrintout = document.getElementById("pendingPrintout")
const dispSettledPrintout = document.getElementById("settledPrintout")